const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config({ path: './.env' });

const User = require('./models/User');
const Restaurant = require('./models/Restaurant');
const FoodItem = require('./models/FoodItem');
const Review = require('./models/Review');

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected for seeding...');

    await User.deleteMany({});
    await Restaurant.deleteMany({});
    await FoodItem.deleteMany({});
    await Review.deleteMany({});

    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@foodflow.ai',
      password: 'admin123',
      role: 'admin',
      phone: '9999999999',
    });

    const user = await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'user123',
      role: 'user',
      phone: '8888888888',
      addresses: [{ label: 'Home', street: '123 Main St', city: 'Mumbai', state: 'Maharashtra', zip: '400001', isDefault: true }],
      preferences: { cuisine: ['Indian', 'Chinese', 'Italian'], spiceLevel: 'medium' },
    });

    const user2 = await User.create({
      name: 'Priya Sharma',
      email: 'priya@example.com',
      password: 'user123',
      role: 'user',
      phone: '7777777777',
      addresses: [{ label: 'Home', street: '456 Park Ave', city: 'Delhi', state: 'Delhi', zip: '110001', isDefault: true }],
      preferences: { cuisine: ['South Indian', 'Healthy'], spiceLevel: 'mild' },
    });

    const restaurants = await Restaurant.create([
      {
        name: 'Spice Kingdom',
        description: 'Authentic Indian vegetarian cuisine with rich flavors and aromatic spices',
        cuisine: ['Indian', 'North Indian', 'Punjabi'],
        rating: 4.5,
        totalRatings: 120,
        priceRange: '$$',
        deliveryFee: 30,
        minOrder: 100,
        deliveryTime: '25-35 min',
        isOpen: true,
        tags: ['curry', 'spicy', 'popular', 'family'],
        featured: true,
        orderCount: 450,
        address: { street: '12 Food Street', city: 'Mumbai', state: 'Maharashtra', zip: '400001' },
        contact: { phone: '9123456789', email: 'spice@foodflow.ai' },
      },
      {
        name: 'Pizza Paradise',
        description: 'Wood-fired pizzas, pasta, and Italian vegetarian specialties',
        cuisine: ['Italian', 'Continental', 'Pizza'],
        rating: 4.3,
        totalRatings: 90,
        priceRange: '$$',
        deliveryFee: 20,
        minOrder: 150,
        deliveryTime: '20-30 min',
        isOpen: true,
        tags: ['pizza', 'pasta', 'italian', 'cheese'],
        featured: true,
        orderCount: 380,
        address: { street: '45 Italian Lane', city: 'Mumbai', state: 'Maharashtra', zip: '400002' },
        contact: { phone: '9234567890', email: 'pizza@foodflow.ai' },
      },
      {
        name: 'Wok Express',
        description: 'Quick Chinese and Asian wok vegetable specialties',
        cuisine: ['Chinese', 'Asian', 'Thai'],
        rating: 4.2,
        totalRatings: 75,
        priceRange: '$',
        deliveryFee: 15,
        minOrder: 80,
        deliveryTime: '15-25 min',
        isOpen: true,
        tags: ['noodles', 'fried rice', 'wok', 'quick'],
        featured: false,
        orderCount: 290,
        address: { street: '78 Asian Avenue', city: 'Mumbai', state: 'Maharashtra', zip: '400003' },
        contact: { phone: '9345678901', email: 'wok@foodflow.ai' },
      },
      {
        name: 'Green Bowl',
        description: 'Healthy salads, smoothies, and nutritious vegetarian bowls',
        cuisine: ['Healthy', 'Vegan', 'Salad'],
        rating: 4.6,
        totalRatings: 65,
        priceRange: '$$',
        deliveryFee: 25,
        minOrder: 120,
        deliveryTime: '20-30 min',
        isOpen: true,
        tags: ['healthy', 'salad', 'vegan', 'organic'],
        featured: true,
        orderCount: 210,
        address: { street: '90 Wellness Road', city: 'Mumbai', state: 'Maharashtra', zip: '400004' },
        contact: { phone: '9456789012', email: 'green@foodflow.ai' },
      },
      {
        name: 'Dosa Express',
        description: 'Authentic South Indian food with crispy dosas and flavorful chutneys',
        cuisine: ['South Indian', 'Indian', 'Healthy'],
        rating: 4.4,
        totalRatings: 95,
        priceRange: '$',
        deliveryFee: 10,
        minOrder: 50,
        deliveryTime: '15-25 min',
        isOpen: true,
        tags: ['dosa', 'idli', 'south-indian', 'breakfast'],
        featured: true,
        orderCount: 520,
        address: { street: '22 Temple Road', city: 'Chennai', state: 'Tamil Nadu', zip: '600001' },
        contact: { phone: '9567890123', email: 'dosa@foodflow.ai' },
      },
      {
        name: 'Taco Fiesta',
        description: 'Vegetarian Mexican food with fresh ingredients and bold flavors',
        cuisine: ['Mexican', 'Continental'],
        rating: 4.1,
        totalRatings: 55,
        priceRange: '$$',
        deliveryFee: 25,
        minOrder: 100,
        deliveryTime: '25-35 min',
        isOpen: true,
        tags: ['taco', 'mexican', 'burrito', 'spicy'],
        featured: false,
        orderCount: 180,
        address: { street: '56 Fiesta Street', city: 'Mumbai', state: 'Maharashtra', zip: '400005' },
        contact: { phone: '9678901234', email: 'taco@foodflow.ai' },
      },
      {
        name: 'Sushi House',
        description: 'Vegetarian Japanese rolls, bowls, and authentic Asian flavors',
        cuisine: ['Japanese', 'Asian', 'Continental'],
        rating: 4.5,
        totalRatings: 70,
        priceRange: '$$$',
        deliveryFee: 35,
        minOrder: 200,
        deliveryTime: '30-40 min',
        isOpen: true,
        tags: ['sushi', 'japanese', 'rice-bowl', 'exotic'],
        featured: false,
        orderCount: 150,
        address: { street: '8 Tokyo Lane', city: 'Mumbai', state: 'Maharashtra', zip: '400006' },
        contact: { phone: '9789012345', email: 'sushi@foodflow.ai' },
      },
      {
        name: 'Sweet Tooth',
        description: 'Desserts, shakes, and sweet treats for every occasion',
        cuisine: ['Dessert', 'Beverage', 'Bakery'],
        rating: 4.7,
        totalRatings: 110,
        priceRange: '$',
        deliveryFee: 15,
        minOrder: 50,
        deliveryTime: '15-20 min',
        isOpen: true,
        tags: ['dessert', 'ice-cream', 'cake', 'sweet'],
        featured: true,
        orderCount: 620,
        address: { street: '7 Sugar Lane', city: 'Mumbai', state: 'Maharashtra', zip: '400007' },
        contact: { phone: '9890123456', email: 'sweet@foodflow.ai' },
      },
    ]);

    const foodItems = await FoodItem.create([
      // Spice Kingdom (Indian)
      {
        name: 'Paneer Butter Masala',
        description: 'Rich creamy paneer curry with butter tomato gravy and kasuri methi',
        price: 220, restaurant: restaurants[0]._id, category: 'Main Course', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.5, totalRatings: 150, orderCount: 350,
        tags: ['paneer', 'creamy', 'popular', 'veg'],
        nutritionalInfo: { calories: 450, protein: 18, carbs: 30, fat: 28 },
      },
      {
        name: 'Dal Makhani',
        description: 'Slow-cooked black lentils with cream butter and aromatic spices',
        price: 180, restaurant: restaurants[0]._id, category: 'Main Course', cuisine: 'Indian',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.6, totalRatings: 130, orderCount: 280,
        tags: ['dal', 'comfort-food', 'popular', 'veg'],
        nutritionalInfo: { calories: 350, protein: 15, carbs: 40, fat: 15 },
      },
      {
        name: 'Veg Biryani',
        description: 'Fragrant basmati rice layered with mixed vegetables and aromatic biryani masala',
        price: 210, restaurant: restaurants[0]._id, category: 'Main Course', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.4, totalRatings: 180, orderCount: 400,
        tags: ['biryani', 'spicy', 'popular', 'veg'],
        nutritionalInfo: { calories: 500, protein: 12, carbs: 85, fat: 14 },
      },
      {
        name: 'Shahi Paneer',
        description: 'Royal paneer curry in a rich creamy cashew and tomato gravy',
        price: 250, restaurant: restaurants[0]._id, category: 'Main Course', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.3, totalRatings: 90, orderCount: 200,
        tags: ['paneer', 'royal', 'creamy', 'veg'],
        nutritionalInfo: { calories: 480, protein: 20, carbs: 25, fat: 32 },
      },
      {
        name: 'Garlic Naan',
        description: 'Tandoor-baked leavened bread topped with garlic and butter',
        price: 50, restaurant: restaurants[0]._id, category: 'Appetizer', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.5, totalRatings: 200, orderCount: 500,
        tags: ['naan', 'bread', 'garlic', 'popular'],
        nutritionalInfo: { calories: 200, protein: 5, carbs: 35, fat: 6 },
      },
      {
        name: 'Veg Seekh Kebab',
        description: 'Spiced vegetable skewers grilled to perfection with mint chutney',
        price: 160, restaurant: restaurants[0]._id, category: 'Appetizer', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.2, totalRatings: 85, orderCount: 190,
        tags: ['kebab', 'appetizer', 'grilled', 'veg'],
        nutritionalInfo: { calories: 280, protein: 10, carbs: 22, fat: 16 },
      },
      {
        name: 'Gulab Jamun',
        description: 'Deep-fried milk solids soaked in rose-flavored sugar syrup',
        price: 80, restaurant: restaurants[0]._id, category: 'Dessert', cuisine: 'Indian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.7, totalRatings: 160, orderCount: 380,
        tags: ['dessert', 'sweet', 'traditional', 'popular'],
        nutritionalInfo: { calories: 320, protein: 3, carbs: 50, fat: 14 },
      },

      // Pizza Paradise (Italian)
      {
        name: 'Margherita Pizza',
        description: 'Classic wood-fired pizza with fresh mozzarella basil and olive oil',
        price: 299, restaurant: restaurants[1]._id, category: 'Main Course', cuisine: 'Italian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.4, totalRatings: 180, orderCount: 420,
        tags: ['pizza', 'cheese', 'vegetarian', 'classic'],
        nutritionalInfo: { calories: 550, protein: 20, carbs: 65, fat: 22 },
      },
      {
        name: 'Pasta Alfredo',
        description: 'Creamy white sauce pasta with mushrooms broccoli and parmesan',
        price: 249, restaurant: restaurants[1]._id, category: 'Main Course', cuisine: 'Italian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.2, totalRatings: 100, orderCount: 280,
        tags: ['pasta', 'creamy', 'vegetarian', 'cheese'],
        nutritionalInfo: { calories: 500, protein: 15, carbs: 60, fat: 24 },
      },
      {
        name: 'Veggie Loaded Pizza',
        description: 'Loaded with bell peppers olives onions mushrooms and sweet corn',
        price: 349, restaurant: restaurants[1]._id, category: 'Main Course', cuisine: 'Italian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.5, totalRatings: 140, orderCount: 350,
        tags: ['pizza', 'veggie', 'loaded', 'popular'],
        nutritionalInfo: { calories: 600, protein: 18, carbs: 72, fat: 26 },
      },
      {
        name: 'Bruschetta',
        description: 'Toasted bread topped with fresh tomatoes basil and balsamic glaze',
        price: 180, restaurant: restaurants[1]._id, category: 'Appetizer', cuisine: 'Italian',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.1, totalRatings: 70, orderCount: 160,
        tags: ['bruschetta', 'appetizer', 'italian', 'starter'],
        nutritionalInfo: { calories: 180, protein: 4, carbs: 28, fat: 6 },
      },
      {
        name: 'Tiramisu',
        description: 'Classic Italian coffee-flavored layered dessert with mascarpone',
        price: 199, restaurant: restaurants[1]._id, category: 'Dessert', cuisine: 'Italian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.6, totalRatings: 95, orderCount: 210,
        tags: ['dessert', 'tiramisu', 'italian', 'coffee'],
        nutritionalInfo: { calories: 380, protein: 6, carbs: 40, fat: 22 },
      },
      {
        name: 'Minestrone Soup',
        description: 'Hearty Italian vegetable soup with pasta beans and herbs',
        price: 150, restaurant: restaurants[1]._id, category: 'Soup', cuisine: 'Italian',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.0, totalRatings: 50, orderCount: 120,
        tags: ['soup', 'healthy', 'italian', 'warm'],
        nutritionalInfo: { calories: 180, protein: 6, carbs: 30, fat: 4, fiber: 8 },
      },

      // Wok Express (Chinese)
      {
        name: 'Veg Hakka Noodles',
        description: 'Stir-fried noodles with mixed vegetables in soy garlic sauce',
        price: 150, restaurant: restaurants[2]._id, category: 'Main Course', cuisine: 'Chinese',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.3, totalRatings: 130, orderCount: 380,
        tags: ['noodles', 'vegetarian', 'quick', 'popular'],
        nutritionalInfo: { calories: 400, protein: 10, carbs: 70, fat: 12 },
      },
      {
        name: 'Veg Manchurian',
        description: 'Crispy vegetable balls tossed in tangy soy Manchurian sauce',
        price: 170, restaurant: restaurants[2]._id, category: 'Appetizer', cuisine: 'Chinese',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.4, totalRatings: 110, orderCount: 320,
        tags: ['manchurian', 'crispy', 'appetizer', 'veg'],
        nutritionalInfo: { calories: 280, protein: 8, carbs: 30, fat: 14 },
      },
      {
        name: 'Fried Rice',
        description: 'Wok-tossed rice with vegetables spring onions and soy sauce',
        price: 160, restaurant: restaurants[2]._id, category: 'Main Course', cuisine: 'Chinese',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.1, totalRatings: 100, orderCount: 290,
        tags: ['rice', 'fried-rice', 'chinese', 'quick'],
        nutritionalInfo: { calories: 380, protein: 8, carbs: 75, fat: 8 },
      },
      {
        name: 'Spring Rolls',
        description: 'Crispy rolls stuffed with seasoned vegetables served with sweet chili sauce',
        price: 140, restaurant: restaurants[2]._id, category: 'Appetizer', cuisine: 'Chinese',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.2, totalRatings: 90, orderCount: 250,
        tags: ['spring-rolls', 'crispy', 'appetizer', 'popular'],
        nutritionalInfo: { calories: 220, protein: 5, carbs: 28, fat: 10 },
      },
      {
        name: 'Hot & Sour Soup',
        description: 'Tangy and spicy vegetarian soup with tofu and bamboo shoots',
        price: 120, restaurant: restaurants[2]._id, category: 'Soup', cuisine: 'Chinese',
        isVegetarian: true, spiceLevel: 'hot', isFeatured: false,
        rating: 4.0, totalRatings: 60, orderCount: 180,
        tags: ['soup', 'hot-sour', 'chinese', 'spicy'],
        nutritionalInfo: { calories: 120, protein: 5, carbs: 15, fat: 3 },
      },
      {
        name: 'Schezwan Noodles',
        description: 'Spicy Schezwan-style noodles with vegetables and chili sauce',
        price: 180, restaurant: restaurants[2]._id, category: 'Main Course', cuisine: 'Chinese',
        isVegetarian: true, spiceLevel: 'hot', isFeatured: false,
        rating: 4.3, totalRatings: 85, orderCount: 230,
        tags: ['noodles', 'spicy', 'schezwan', 'popular'],
        nutritionalInfo: { calories: 420, protein: 10, carbs: 72, fat: 14 },
      },

      // Green Bowl (Healthy)
      {
        name: 'Greek Salad',
        description: 'Fresh vegetables with feta cheese olives and olive lemon dressing',
        price: 199, restaurant: restaurants[3]._id, category: 'Salad', cuisine: 'Continental',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.5, totalRatings: 80, orderCount: 220,
        tags: ['salad', 'healthy', 'fresh', 'vegetarian'],
        nutritionalInfo: { calories: 250, protein: 8, carbs: 15, fat: 18, fiber: 6 },
      },
      {
        name: 'Quinoa Power Bowl',
        description: 'Protein-packed quinoa bowl with avocado chickpeas and tahini dressing',
        price: 280, restaurant: restaurants[3]._id, category: 'Main Course', cuisine: 'Healthy',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.5, totalRatings: 70, orderCount: 190,
        tags: ['quinoa', 'protein', 'healthy', 'bowl'],
        nutritionalInfo: { calories: 350, protein: 16, carbs: 42, fat: 14, fiber: 10 },
      },
      {
        name: 'Acai Smoothie Bowl',
        description: 'Antioxidant-rich acai bowl with granola fresh fruits and chia seeds',
        price: 249, restaurant: restaurants[3]._id, category: 'Breakfast', cuisine: 'Healthy',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.7, totalRatings: 60, orderCount: 190,
        tags: ['smoothie', 'healthy', 'vegan', 'breakfast'],
        nutritionalInfo: { calories: 300, protein: 6, carbs: 55, fat: 8, fiber: 8 },
      },
      {
        name: 'Grilled Veggie Wrap',
        description: 'Whole wheat wrap with grilled zucchini bell peppers and hummus',
        price: 220, restaurant: restaurants[3]._id, category: 'Main Course', cuisine: 'Healthy',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.3, totalRatings: 55, orderCount: 150,
        tags: ['wrap', 'healthy', 'grilled', 'vegan'],
        nutritionalInfo: { calories: 320, protein: 10, carbs: 40, fat: 12, fiber: 7 },
      },
      {
        name: 'Fruit Smoothie',
        description: 'Blend of fresh mango banana berries and almond milk',
        price: 150, restaurant: restaurants[3]._id, category: 'Beverage', cuisine: 'Healthy',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.6, totalRatings: 90, orderCount: 260,
        tags: ['smoothie', 'healthy', 'drink', 'refreshing'],
        nutritionalInfo: { calories: 180, protein: 3, carbs: 38, fat: 2, fiber: 5 },
      },
      {
        name: 'Avocado Toast',
        description: 'Sourdough toast with mashed avocado cherry tomatoes and sesame seeds',
        price: 200, restaurant: restaurants[3]._id, category: 'Breakfast', cuisine: 'Healthy',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.4, totalRatings: 65, orderCount: 170,
        tags: ['avocado', 'toast', 'breakfast', 'healthy'],
        nutritionalInfo: { calories: 280, protein: 7, carbs: 30, fat: 15, fiber: 8 },
      },

      // Dosa Express (South Indian)
      {
        name: 'Masala Dosa',
        description: 'Crispy rice crepe filled with spiced potato filling served with chutneys',
        price: 120, restaurant: restaurants[4]._id, category: 'Breakfast', cuisine: 'South Indian',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.6, totalRatings: 200, orderCount: 500,
        tags: ['dosa', 'south-indian', 'breakfast', 'popular'],
        nutritionalInfo: { calories: 300, protein: 8, carbs: 50, fat: 8 },
      },
      {
        name: 'Idli Sambar',
        description: 'Steamed rice lentil cakes served with lentil soup and coconut chutney',
        price: 80, restaurant: restaurants[4]._id, category: 'Breakfast', cuisine: 'South Indian',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.5, totalRatings: 180, orderCount: 450,
        tags: ['idli', 'south-indian', 'healthy', 'breakfast'],
        nutritionalInfo: { calories: 200, protein: 8, carbs: 38, fat: 2, fiber: 5 },
      },
      {
        name: 'Vada',
        description: 'Crispy lentil donuts served with sambar and coconut chutney',
        price: 70, restaurant: restaurants[4]._id, category: 'Appetizer', cuisine: 'South Indian',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.3, totalRatings: 120, orderCount: 300,
        tags: ['vada', 'crispy', 'south-indian', 'snack'],
        nutritionalInfo: { calories: 180, protein: 7, carbs: 22, fat: 8 },
      },
      {
        name: 'Rava Dosa',
        description: 'Crispy semolina crepe with onions and green chilies',
        price: 130, restaurant: restaurants[4]._id, category: 'Breakfast', cuisine: 'South Indian',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.4, totalRatings: 110, orderCount: 280,
        tags: ['dosa', 'rava', 'crispy', 'popular'],
        nutritionalInfo: { calories: 280, protein: 6, carbs: 45, fat: 10 },
      },
      {
        name: 'Uttapam',
        description: 'Thick rice pancake topped with onions tomatoes and green chilies',
        price: 100, restaurant: restaurants[4]._id, category: 'Breakfast', cuisine: 'South Indian',
        isVegetarian: true, isVegan: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.2, totalRatings: 80, orderCount: 200,
        tags: ['uttapam', 'south-indian', 'breakfast', 'healthy'],
        nutritionalInfo: { calories: 240, protein: 6, carbs: 42, fat: 6 },
      },
      {
        name: 'Filter Coffee',
        description: 'Traditional South Indian filter coffee with frothy milk',
        price: 40, restaurant: restaurants[4]._id, category: 'Beverage', cuisine: 'South Indian',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.8, totalRatings: 250, orderCount: 600,
        tags: ['coffee', 'south-indian', 'beverage', 'classic'],
        nutritionalInfo: { calories: 60, protein: 2, carbs: 8, fat: 2 },
      },

      // Taco Fiesta (Mexican)
      {
        name: 'Veg Tacos',
        description: 'Crispy corn tacos filled with beans corn salsa and guacamole',
        price: 220, restaurant: restaurants[5]._id, category: 'Main Course', cuisine: 'Mexican',
        isVegetarian: true, isVegan: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.3, totalRatings: 70, orderCount: 200,
        tags: ['taco', 'mexican', 'crispy', 'veg'],
        nutritionalInfo: { calories: 350, protein: 10, carbs: 42, fat: 16 },
      },
      {
        name: 'Burrito Bowl',
        description: 'Rice bowl with black beans corn salsa sour cream and guacamole',
        price: 280, restaurant: restaurants[5]._id, category: 'Main Course', cuisine: 'Mexican',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.2, totalRatings: 50, orderCount: 140,
        tags: ['burrito', 'bowl', 'mexican', 'hearty'],
        nutritionalInfo: { calories: 450, protein: 14, carbs: 55, fat: 18, fiber: 10 },
      },
      {
        name: 'Nachos Supreme',
        description: 'Loaded tortilla chips with cheese sauce beans jalapenos and salsa',
        price: 250, restaurant: restaurants[5]._id, category: 'Appetizer', cuisine: 'Mexican',
        isVegetarian: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.4, totalRatings: 85, orderCount: 240,
        tags: ['nachos', 'cheese', 'snack', 'popular'],
        nutritionalInfo: { calories: 420, protein: 12, carbs: 45, fat: 22 },
      },
      {
        name: 'Quesadilla',
        description: 'Grilled tortilla with melted cheese mushrooms and bell peppers',
        price: 240, restaurant: restaurants[5]._id, category: 'Main Course', cuisine: 'Mexican',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.1, totalRatings: 45, orderCount: 130,
        tags: ['quesadilla', 'cheese', 'mexican', 'grilled'],
        nutritionalInfo: { calories: 380, protein: 14, carbs: 35, fat: 20 },
      },
      {
        name: 'Mexican Rice',
        description: 'Spiced rice with corn bell peppers beans and tomato sauce',
        price: 190, restaurant: restaurants[5]._id, category: 'Main Course', cuisine: 'Mexican',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'medium', isFeatured: false,
        rating: 4.0, totalRatings: 40, orderCount: 110,
        tags: ['rice', 'mexican', 'spicy', 'vegan'],
        nutritionalInfo: { calories: 320, protein: 8, carbs: 58, fat: 8, fiber: 6 },
      },

      // Sushi House (Japanese)
      {
        name: 'Veg Sushi Roll',
        description: 'Avocado cucumber and carrot rolled in seasoned rice and nori',
        price: 320, restaurant: restaurants[6]._id, category: 'Main Course', cuisine: 'Japanese',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.5, totalRatings: 60, orderCount: 160,
        tags: ['sushi', 'japanese', 'veg', 'exotic'],
        nutritionalInfo: { calories: 280, protein: 6, carbs: 45, fat: 8 },
      },
      {
        name: 'Edamame',
        description: 'Steamed young soybeans seasoned with sea salt',
        price: 150, restaurant: restaurants[6]._id, category: 'Appetizer', cuisine: 'Japanese',
        isVegetarian: true, isVegan: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.2, totalRatings: 40, orderCount: 110,
        tags: ['edamame', 'japanese', 'appetizer', 'protein'],
        nutritionalInfo: { calories: 180, protein: 16, carbs: 14, fat: 6, fiber: 7 },
      },
      {
        name: 'Miso Soup',
        description: 'Traditional Japanese soybean soup with tofu seaweed and spring onions',
        price: 120, restaurant: restaurants[6]._id, category: 'Soup', cuisine: 'Japanese',
        isVegetarian: true, isVegan: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.3, totalRatings: 55, orderCount: 150,
        tags: ['miso', 'soup', 'japanese', 'healthy'],
        nutritionalInfo: { calories: 80, protein: 4, carbs: 8, fat: 2 },
      },
      {
        name: 'Veg Ramen',
        description: 'Japanese noodle soup in miso broth with vegetables and tofu',
        price: 290, restaurant: restaurants[6]._id, category: 'Main Course', cuisine: 'Japanese',
        isVegetarian: true, isVegan: true, spiceLevel: 'medium', isFeatured: true,
        rating: 4.4, totalRatings: 50, orderCount: 130,
        tags: ['ramen', 'noodles', 'japanese', 'soup'],
        nutritionalInfo: { calories: 380, protein: 12, carbs: 52, fat: 12 },
      },
      {
        name: 'Vegetable Tempura',
        description: 'Lightly battered and deep-fried seasonal vegetables with dipping sauce',
        price: 260, restaurant: restaurants[6]._id, category: 'Appetizer', cuisine: 'Japanese',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.3, totalRatings: 45, orderCount: 120,
        tags: ['tempura', 'crispy', 'japanese', 'appetizer'],
        nutritionalInfo: { calories: 300, protein: 5, carbs: 28, fat: 18 },
      },

      // Sweet Tooth (Desserts)
      {
        name: 'Belgian Waffle',
        description: 'Crispy golden waffle topped with fresh strawberries and whipped cream',
        price: 199, restaurant: restaurants[7]._id, category: 'Dessert', cuisine: 'Bakery',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.6, totalRatings: 140, orderCount: 380,
        tags: ['waffle', 'dessert', 'sweet', 'popular'],
        nutritionalInfo: { calories: 380, protein: 6, carbs: 48, fat: 18 },
      },
      {
        name: 'Chocolate Shake',
        description: 'Thick and creamy chocolate milkshake with whipped cream and cherry',
        price: 150, restaurant: restaurants[7]._id, category: 'Beverage', cuisine: 'Bakery',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.7, totalRatings: 180, orderCount: 480,
        tags: ['shake', 'chocolate', 'beverage', 'popular'],
        nutritionalInfo: { calories: 350, protein: 8, carbs: 50, fat: 14 },
      },
      {
        name: 'Brownie Sundae',
        description: 'Warm chocolate brownie with vanilla ice cream fudge sauce and nuts',
        price: 220, restaurant: restaurants[7]._id, category: 'Dessert', cuisine: 'Bakery',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.5, totalRatings: 130, orderCount: 340,
        tags: ['brownie', 'sundae', 'ice-cream', 'dessert'],
        nutritionalInfo: { calories: 450, protein: 6, carbs: 55, fat: 24 },
      },
      {
        name: 'Fruit Ice Cream',
        description: 'Assorted fruit flavored ice cream scoops with fresh fruit topping',
        price: 120, restaurant: restaurants[7]._id, category: 'Dessert', cuisine: 'Bakery',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.4, totalRatings: 100, orderCount: 280,
        tags: ['ice-cream', 'fruit', 'dessert', 'cold'],
        nutritionalInfo: { calories: 200, protein: 3, carbs: 32, fat: 8 },
      },
      {
        name: 'Mango Lassi',
        description: 'Creamy yogurt drink blended with ripe mangoes and cardamom',
        price: 110, restaurant: restaurants[7]._id, category: 'Beverage', cuisine: 'Indian',
        isVegetarian: true, isGlutenFree: true, spiceLevel: 'mild', isFeatured: false,
        rating: 4.5, totalRatings: 160, orderCount: 420,
        tags: ['lassi', 'mango', 'drink', 'refreshing'],
        nutritionalInfo: { calories: 180, protein: 4, carbs: 32, fat: 4 },
      },
      {
        name: 'Cheesecake',
        description: 'New York style baked cheesecake with berry compote',
        price: 250, restaurant: restaurants[7]._id, category: 'Dessert', cuisine: 'Bakery',
        isVegetarian: true, spiceLevel: 'mild', isFeatured: true,
        rating: 4.6, totalRatings: 120, orderCount: 310,
        tags: ['cheesecake', 'dessert', 'baked', 'classic'],
        nutritionalInfo: { calories: 420, protein: 8, carbs: 35, fat: 28 },
      },
    ]);

    const reviews = await Review.create([
      {
        user: user._id, foodItem: foodItems[0]._id, restaurant: restaurants[0]._id,
        rating: 5, title: 'Best paneer ever!', comment: 'The paneer butter masala was absolutely delicious. Creamy and perfectly spiced.',
        isVerifiedPurchase: true,
      },
      {
        user: user2._id, foodItem: foodItems[1]._id, restaurant: restaurants[0]._id,
        rating: 4, title: 'Comfort food', comment: 'Dal makhani was very tasty. Reminded me of home-cooked food.',
        isVerifiedPurchase: true,
      },
      {
        user: user._id, foodItem: foodItems[7]._id, restaurant: restaurants[1]._id,
        rating: 5, comment: 'Best pizza in town! The crust is perfect and the cheese is so fresh.',
        isVerifiedPurchase: true,
      },
      {
        user: user2._id, foodItem: foodItems[11]._id, restaurant: restaurants[1]._id,
        rating: 4, comment: 'Tiramisu was fantastic. Authentic Italian taste.',
        isVerifiedPurchase: true,
      },
      {
        user: user._id, foodItem: foodItems[25]._id, restaurant: restaurants[4]._id,
        rating: 5, comment: 'Masala dosa was crispy and perfect. The chutneys were amazing!',
        isVerifiedPurchase: true,
      },
      {
        user: user2._id, foodItem: foodItems[36]._id, restaurant: restaurants[6]._id,
        rating: 5, comment: 'The veg sushi roll was fresh and beautifully presented.',
        isVerifiedPurchase: true,
      },
      {
        user: user._id, foodItem: foodItems[41]._id, restaurant: restaurants[7]._id,
        rating: 5, comment: 'Belgian waffle is a must-try! Crispy outside, soft inside.',
        isVerifiedPurchase: true,
      },
      {
        user: user2._id, foodItem: foodItems[43]._id, restaurant: restaurants[7]._id,
        rating: 4, comment: 'Brownie sundae was rich and decadent. Perfect for chocolate lovers.',
        isVerifiedPurchase: true,
      },
    ]);

    console.log('==============================');
    console.log('Seed data inserted successfully!');
    console.log('==============================');
    console.log(`Admin: admin@foodflow.ai / admin123`);
    console.log(`Users: john@example.com / user123`);
    console.log(`       priya@example.com / user123`);
    console.log('---');
    console.log(`Restaurants: ${restaurants.length}`);
    console.log(`Food Items: ${foodItems.length} (All Pure Veg!)`);
    console.log(`Reviews: ${reviews.length}`);
    console.log('==============================');

    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedData();
